<?php

namespace kbrabrand\tinymce\assets\tinymce;

use craft\web\AssetBundle;

/**
 * TinyMCE asset bundle.
 *
 * @author Kristoffer Brabrand <kristoffer@brabrand.no>
 * @since 1.0
 */
class TinymceAsset extends AssetBundle
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->sourcePath = dirname(__DIR__, 3).'/lib/tinymce/dist';
        $this->js = [
            'tinymce.min.js',
        ];

        parent::init();
    }

    /**
     * @inheritdoc
     */
    public function registerAssetFiles($view)
    {
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub

        $css = <<<CSS
.ck-editor__editable {
    background: #fff !important;
}
CSS;
        $view->registerCss($css);
    }
}
